apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  serviceName: elasticsearch
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
        ports:
          - containerPort: 9200
          - containerPort: 9300
        env:
          - name: discovery.type
            value: single-node
          - name: ES_JAVA_OPTS
            value: "{{ .Values.elasticsearch.esJavaOpts }}"
          - name: xpack.security.enabled
            value: "{{ default "false" .Values.elasticsearch.security.enabled }}"
        resources:
          limits:
            cpu: {{ .Values.elasticsearch.resources.limits.cpu }}
            memory: {{ .Values.elasticsearch.resources.limits.memory }}
          requests:
            cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
            memory: {{ .Values.elasticsearch.resources.requests.memory }}
        volumeMounts:
          - name: es-data
            mountPath: /usr/share/elasticsearch/data
        readinessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 40
          periodSeconds: 20
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc